name: Docker build and push

on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest


    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with: 
        username: ${{secrets.DOCKER_USERNAME}}
        username: ${{secrets.DOCKER_PASSWORD}}
        
     - name: Build and Push Api image
       uses: docker/build-push-action@v5
       with:
        context: .
        file: Dockerfile.Api
        push: true
        tags: |
            ${{ secrets.DOCKER_USERNAME }}/notification-api:latest
            ${{ secrets.DOCKER_USERNAME }}/notification-api:${{ github.sha }}
            - name: Build & Push Worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.Worker
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/notification-worker:latest
            ${{ secrets.DOCKER_USERNAME }}/notification-worker:${{ github.sha }}   
