name: frontend ci

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
    pull_request:
      - "frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Node.jobs
       uses : actions/setup-node@v4
       with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: frontend/notification-ui/package-lock.json

     - name: install depedencies
       run: npm ci
       working-directory: frontend/notification-ui

     - name: Build frontend
       run: npm run build
       working-directory: frontend/notification-ui                  